version: "3.7"

volumes:
  db_data:

services:
  test-db:
    profiles: ["test"]
    image: postgres:13.3-alpine
    restart: always
    env_file: .env-test
    ports:
      - "5433:5432"

  test:
    profiles: ["test"]
    build: ./src
    restart: "no"
    env_file: .env-test
    depends_on:
      - test-db
    command: "pytest"

  db:
    profiles: ["local"]
    image: postgres:13.3-alpine
    restart: always
    env_file: .env
    ports:
      - "5432:5432"
    volumes:
          - "db_data:/var/lib/postgresql/data/"

  app:
    profiles: ["local"]
    build: ./src
    restart: always
    env_file: .env
    depends_on:
      - db
    ports:
      - "${APP_PORT:-8000}:${APP_PORT:-8000}"
